apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/$GOOGLE_CLOUD_PROJECT/$IMAGE_TAG
deploy:
  kubectl:
    manifests:
      - helloworld_client/k8s-helloworld_client.yaml
      - helloworld_server/k8s-helloworld_server.yaml
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: k8s-skaffold
