apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/$GOOGLE_CLOUD_PROJECT/$GOOGLE_CLOUD_PROJECT-labs/tracing-$APPLICATION_SERVER
    workspace: ./$APPLICATION_SERVER/
  - imageName: gcr.io/$GOOGLE_CLOUD_PROJECT/$GOOGLE_CLOUD_PROJECT-labs/tracing-$APPLICATION_CLIENT
    workspace: ./$APPLICATION_CLIENT/
deploy:
  kubectl:
    manifests:
      - $APPLICATION_CLIENT/k8s-$APPLICATION_CLIENT.yaml
      - $APPLICATION_SERVER/k8s-$APPLICATION_SERVER.yaml
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: k8s-skaffold
