apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  labels:
    run: $APPLICATION_CLIENT
  name: $APPLICATION_CLIENT
spec:
  concurrencyPolicy: Allow
  backoffLimit: 5
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: $APPLICATION_CLIENT
        spec:
            containers:
            - image: gcr.io/$GOOGLE_CLOUD_PROJECT/$GOOGLE_CLOUD_PROJECT-labs/tracing-$APPLICATION_CLIENT
              name: $APPLICATION_CLIENT
              env:
              - name: PROJECT_ID
                value: $GOOGLE_CLOUD_PROJECT
              - name: APPLICATION_SERVER
                value: $APPLICATION_SERVER
              resources:
                requests:
                  cpu: 200m
            restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}