apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: $APPLICATION_SERVER-service
spec:
  ports:
  - port: $APPLICATION_SERVER_PORT
    protocol: TCP
    targetPort: $APPLICATION_SERVER_PORT
  selector:
    run: $APPLICATION_SERVER
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $APPLICATION_SERVER-ingress
spec:
  backend:
    serviceName: $APPLICATION_SERVER-service
    servicePort: $APPLICATION_SERVER_PORT
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: $APPLICATION_SERVER
  name: $APPLICATION_SERVER
spec:
  replicas: 1
  selector:
    matchLabels:
      run: $APPLICATION_SERVER
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: $APPLICATION_SERVER
    spec:
      containers:
      - image: gcr.io/$GOOGLE_CLOUD_PROJECT/$GOOGLE_CLOUD_PROJECT-labs/tracing-$APPLICATION_SERVER
        name: $APPLICATION_SERVER
        env:
        - name: PROJECT_ID
          value: $GOOGLE_CLOUD_PROJECT
        - name: "GOOGLE_APPLICATION_CREDENTIALS"
          value: "/var/run/secret/cloud.google.com/key.json"
        ports:
        - containerPort: $APPLICATION_SERVER_PORT
          name: http
        - containerPort: $TRACING_PORT
          name: ztraces
        volumeMounts:
        - name: "service-account"
          mountPath: "/var/run/secret/cloud.google.com"
        resources:
          requests:
            cpu: 200m
      volumes:
      - name: "service-account"
        secret:
          secretName: "stackdriver-secret"
status: {}
