apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: $APPLICATION_SERVER
spec:
  ports:
  - port: $APPLICATION_SERVER_PORT
    protocol: TCP
    targetPort: $APPLICATION_SERVER_PORT
  selector:
    run: $APPLICATION_SERVER
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: $APPLICATION_SERVER
  name: $APPLICATION_SERVER
spec:
  replicas: 1
  selector:
    matchLabels:
      run: $APPLICATION_SERVER
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: $APPLICATION_SERVER
    spec:
      containers:
      - image: gcr.io/$GOOGLE_CLOUD_PROJECT/$GOOGLE_CLOUD_PROJECT-labs/tracing-$APPLICATION_SERVER
        name: $APPLICATION_SERVER
        ports:
        - containerPort: $APPLICATION_SERVER_PORT
          name: http
        - containerPort: $TRACING_PORT
          name: ztraces
        resources:
          requests:
            cpu: 200m
status: {}
